services:
  - type: web
    name: ql-vatlieu-congtruong
    runtime: node
    plan: free
    region: singapore # Chọn khu vực gần Việt Nam nhất để tốc độ nhanh
    buildCommand: ""
    startCommand: node src/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
