services:
  - type: web
    name: ql-vatlieu-congtruong
    runtime: node
    plan: free
    region: singapore
    buildCommand: echo Build OK
    startCommand: node src/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
